### ISSUE TITLE
reading the status of the device 

### ISSUE THREAD

**Issue by HKhudr** [MAFFPT/hubitat-Sonoff-switch-DIY-mode#1]
Hi,
Thank you for this code.  IT works fine when i give the command from hubitat to the device.  If I change the status of the device like on sonoff Mini  from on to off by pressing the switch on the device it will not update the device on hubitat unless i do refresh.
Is there a way to fix that without overloading the hubitat with messages?
Thank you

**Comment by MAFFPT** [comment]
Hi @HKhudr,

I did a quick search now and I think that the callback is not possible.

I'l check it this weekend.

**Comment by MAFFPT** [comment]
Hi @HKhudr,

I had time to check it out this morning and, I'm afraid, I bad news: it's really not possible to get any information about the device status change back to Hubitat - as a matter of facts, no place at all. The available DIY API doesn't have any option to do that. 

I could see that it seems to be possible using eWeLink (original Sonoff) API, but it would need to dig further, and, to be honest with you, I'm full of services to do now and I don't have time for it - a guy must pay his bills ...

**Comment by HKhudr** [comment]
Thank you for your prompt reply and for your time to check.   No problem at all.   I think I should tasmotize them.
